# Generated by Django 5.1.2 on 2024-11-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
    ]
